" -- linkファイル配備
" ln -s ~/dotfiles/vim/vimrc ~/.vimrc

" --- vim保存場所
" ~/.vimrc

" --- 基本設定 ---
syntax on                  " シンタックスハイライトを有効にする
set number                 " 行番号を表示
set showcmd                " コマンド入力をステータスに表示
set showmode               " ノーマル/インサートなど表示
set clipboard=unnamedplus " OSのクリップボードと連携（macOS/Windowsならおすすめ）

" --- タブ・インデント ---
set tabstop=4              " タブ幅を4スペースに
set shiftwidth=4           " 自動インデントの幅
set expandtab              " タブをスペースに変換

" --- 検索 ---
set ignorecase             " 検索時に大文字小文字を区別しない
set smartcase              " 大文字を含むときは区別する
set incsearch              " インクリメンタルサーチ（入力中に即検索）
set hlsearch               " 検索結果をハイライト

" --- 操作性 ---
set mouse=a                " マウス操作を有効に
set cursorline             " カーソル行をハイライト
set wildmenu               " コマンド補完のメニューを表示
set autoread               " 外部変更を自動で読み込み

" --- ファイル ---
set nobackup               " バックアップファイルを作らない
set nowritebackup
set noswapfile             " スワップファイルを作らない
