#!/usr/bin/env bash

# PureLine - A Pure Bash Powerline PS1 Command Prompt

# clear all variables and declare to prevent issues when re-sourcing
unset PL_SYMBOLS;  declare -A PL_SYMBOLS   # Hash table to reference symbols
unset PL_COLORS;   declare -A PL_COLORS    # Hash table to reference colors
unset PL_SEGMENTS; declare -a PL_SEGMENTS  # Array to hold segments and their arguments

# -----------------------------------------------------------------------------
# returns a string with the powerline symbol for a segment end
# arg: $1 is foreground color of the next segment
# arg: $2 is background color of the next segment
function segment_end {
    local end_char
    local fg
    if [ "$__last_color" == "$2" ]; then
        # segment colors are the same, use a foreground separator
        end_char="${PL_SYMBOLS[soft_separator]}"
        fg="$1"
    else
        # segment colors are different, use a background separator
        end_char="${PL_SYMBOLS[hard_separator]}"
        fg="$__last_color"
    fi
    if [ -n "$__last_color" ]; then
        echo "${PL_COLORS[$fg]}${PL_COLORS[On_$2]}$end_char"
    fi
}

# -----------------------------------------------------------------------------
# returns a string with background and foreground colours set
# arg: $1 foreground color
# arg: $2 background color
# arg: $3 content
function segment_content {
    __last_color="$2"
    echo "${PL_COLORS[$1]}${PL_COLORS[On_$2]}$3"
}

#------------------------------------------------------------------------------
# Helper function for User segment - also used in external ssh segment
function ip_address {
    local ip_address
    local ip_loc
    local ifconfig_loc

    if ip_loc="$(type -p "ip")" || [[ -n $ip_loc ]]; then
        ip_address="$(ip route get 1 | tr -s ' ' | cut -d' ' -f7)"
    elif ifconfig_loc="$(type -p "ifconfig")" || [[ -n $ifconfig_loc ]]; then
        while IFS=$': \t' read -ra _line ;do
            [ -z "${_line%inet}"   ] &&
                _ip=${_line[${#_line[1]}>4?1:2]} &&
                [ "${_ip#127.0.0.1}"   ] && ip_address=$_ip
        done< <(LANG=C /sbin/ifconfig)
    else
        ip_address="127.0.0.1"
    fi
    echo $ip_address
}

#------------------------------------------------------------------------------
# Helper function to return normal or super user prompt character
function prompt_char {
    [[ ${EUID} -eq 0 ]] && echo "#" || echo "\$"
}

# -----------------------------------------------------------------------------
# append to prompt: current time
# arg: $1 background color
# arg: $2 foreground color
# optional variables;
#   PL_TIME_SHOW_SECONDS: true/false for hh:mm:ss / hh:mm
function time_segment {
    local bg_color="$1"
    local fg_color="$2"

    # 現在の時刻のHourを取得
    current_hour=$(date +"%H")

    if [ "$current_hour" -eq 1 ] || [ "$current_hour" -eq 13 ]; then
        local clock_icon="🕐 "
    elif [ "$current_hour" -eq 2 ] || [ "$current_hour" -eq 14 ]; then
        local clock_icon="🕑 "
    elif [ "$current_hour" -eq 3 ] || [ "$current_hour" -eq 15 ]; then
        local clock_icon="🕒 "
    elif [ "$current_hour" -eq 4 ] || [ "$current_hour" -eq 16 ]; then
        local clock_icon="🕓 "
    elif [ "$current_hour" -eq 5 ] || [ "$current_hour" -eq 17 ]; then
        local clock_icon="🕔 "
    elif [ "$current_hour" -eq 6 ] || [ "$current_hour" -eq 18 ]; then
        local clock_icon="🕕 "
    elif [ "$current_hour" -eq 7 ] || [ "$current_hour" -eq 19 ]; then
        local clock_icon="🕖 "
    elif [ "$current_hour" -eq 8 ] || [ "$current_hour" -eq 20 ]; then
        local clock_icon="🕗 "
    elif [ "$current_hour" -eq 9 ] || [ "$current_hour" -eq 21 ]; then
        local clock_icon="🕘 "
    elif [ "$current_hour" -eq 10 ] || [ "$current_hour" -eq 22 ]; then
        local clock_icon="🕙 "
    elif [ "$current_hour" -eq 11 ] || [ "$current_hour" -eq 23 ]; then
        local clock_icon="🕙 "
    elif [ "$current_hour" -eq 12 ] || [ "$current_hour" -eq 0 ]; then
        local clock_icon="🕛 "
    else
        local clock_icon="💣 "
    fi



    if [ "$current_hour" -ge 6 ] && [ "$current_hour" -le 9 ]; then
        local moon_icon="🌕 "
    elif [ "$current_hour" -ge 10 ] && [ "$current_hour" -le 12 ]; then
        local moon_icon="🌖 "
    elif [ "$current_hour" -ge 13 ] && [ "$current_hour" -le 14 ]; then
        local moon_icon="🌗 "
    elif [ "$current_hour" -ge 15 ] && [ "$current_hour" -le 17 ]; then
        local moon_icon="🌘 "
    else
        local moon_icon="🌑 "
    fi

    if [ "$PL_T&&IME_SHOW_SECONDS" = true ]; then
        local content="${moon_icon}${clock_icon}\t"
        #local content="\t"
    else
        local content="${moon_icon}${clock_icon}\A"
        #local content="\A"
    fi
    PS1+="$(segment_end "$fg_color" "$bg_color")"
    PS1+="$(segment_content "$fg_color" "$bg_color" " $content ")"
    __last_color="$bg_color"
}

#------------------------------------------------------------------------------
# append to prompt: user@host or user or root@host
# arg: $1 background color
# arg: $2 foreground color
# option variables;
#   PL_USER_SHOW_HOST: true/false to show host name/ip
#   PL_USER_USE_IP: true/false to show IP instead of hostname
function user_segment {
    local bg_color="$1"
    local fg_color="$2"
    local content="\u"
    # Show host if true or when user is remote/root
    if [ "$PL_USER_SHOW_HOST" = true ]; then
        if [ "$PL_USER_USE_IP" = true ]; then
            content+="@$(ip_address)"
        else
            content+="@\h"
        fi
    fi
    PS1+="$(segment_end "$fg_color" "$bg_color")"
    PS1+="$(segment_content "$fg_color" "$bg_color" " $content ")"
    __last_color="$bg_color"
}

# -----------------------------------------------------------------------------
# append to prompt: current directory
# arg: $1 background color
# arg: $2 foreground color
# option variables;
#   PL_PATH_TRIM: 0—fullpath, 1—current dir, [x]—trim to x number of dir
function path_segment {
    local bg_color="$1"
    local fg_color="$2"
    local content="\w"
    if [ "$PL_PATH_TRIM" -eq 1 ]; then
        local content="\W"
    elif [ "$PL_PATH_TRIM" -gt 1 ]; then
        PROMPT_DIRTRIM="$PL_PATH_TRIM"
    fi
    PS1+="$(segment_end "$fg_color" "$bg_color")"
    PS1+="$(segment_content "$fg_color" "$bg_color" " $content ")"
    __last_color="$bg_color"
}

# -----------------------------------------------------------------------------
# append to prompt: the number of background jobs running
# arg: $1 background color
# arg: $2 foreground color
function background_jobs_segment {
    local bg_color="$1"
    local fg_color="$2"
    local number_jobs
    number_jobs=$(jobs | grep -cv "Done" | tr -d '[:space:]')
    if [ ! "$number_jobs" -eq 0 ]; then
        PS1+="$(segment_end "$fg_color" "$bg_color")"
        PS1+="$(segment_content "$fg_color" "$bg_color" " ${PL_SYMBOLS[background_jobs]} $number_jobs ")"
        __last_color="$bg_color"
    fi
}

# -----------------------------------------------------------------------------
# append to prompt: indicator is the current directory is ready-only
# arg: $1 background color
# arg: $2 foreground color
function read_only_segment {
    local bg_color="$1"
    local fg_color="$2"
    if [ ! -w "$PWD" ]; then
        PS1+="$(segment_end "$fg_color" "$bg_color")"
        PS1+="$(segment_content "$fg_color" "$bg_color" " ${PL_SYMBOLS[read_only]} ")"
        __last_color="$bg_color"
    fi
}

# -----------------------------------------------------------------------------
# append to prompt: append the normal '$' or super-user '#' prompt character
# arg: $1 background color
# arg: $2 foreground color
# option variables;
#   PL_PROMPT_SHOW_SHLVL: true/relative/false to show the shell level
#       true      Show the value of $SHLVL
#       relative  Show the shell level relatively to the first shell sourcing pureline.
#                   Useful when that first shell is already a sub-shell,
#                   like in vscode integrated terminals.
#       false     Show nothing
function prompt_segment {
    local bg_color="$1"
    local fg_color="$2"

    if [[ -n $PL_PROMPT_SHOW_SHLVL ]]; then
        # create local variable 'shell_level' ...
        if [[ $PL_PROMPT_SHOW_SHLVL == true ]]; then
            local shell_level=$SHLVL
        elif [[ $PL_PROMPT_SHOW_SHLVL == relative ]]; then
            [[ -v __pl_starting_shlvl ]] || export __pl_starting_shlvl=$SHLVL
            local shell_level=$((SHLVL - __pl_starting_shlvl + 1))
        fi
        # ... except if its value is 1
        ((shell_level != 1)) || unset shell_level
    fi

    local content
    content=" ${shell_level:-}$(prompt_char) "
    if [ ${EUID} -eq 0 ]; then
        if [ -n "$PL_PROMPT_ROOT_FG" ]; then
            fg_color="$PL_PROMPT_ROOT_FG"
        fi
        if [ -n "$PL_PROMPT_ROOT_BG" ]; then
            bg_color="$PL_PROMPT_ROOT_BG"
        fi
    fi
    PS1+="$(segment_end "$fg_color" "$bg_color")"
    PS1+="$(segment_content "$fg_color" "$bg_color" "$content")"
    __last_color="$bg_color"
}

# -----------------------------------------------------------------------------
# append to prompt: return code for previous command
# arg: $1 background color
# arg: $2 foreground color
function return_code_segment {
    if [ ! "$__return_code" -eq 0 ]; then
        local bg_color="$1"
        local fg_color="$2"
        local content=" ${PL_SYMBOLS[return_code]} $__return_code "
        PS1+="$(segment_end "$fg_color" "$bg_color")"
        PS1+="$(segment_content "$fg_color" "$bg_color" "$content")"
        __last_color="$bg_color"
    fi
}

# -----------------------------------------------------------------------------
# append to prompt: end the current promptline and start a newline
function newline_segment {
    if [ -n "$__last_color" ]; then
        PS1+="$(segment_end "$__last_color" 'Default')"
    fi
    PS1+="\n"
    unset __last_color
}

# -----------------------------------------------------------------------------
# code to run before processing the inherited $PROMPT_COMMAND
function __pureline_pre {
    __return_code=$?                    # save return code of last command

    if [[ -n $PL_TITLEBAR ]]; then
        if (( ${BASH_VERSINFO[0]:-0} > 4 || (${BASH_VERSINFO[0]:-0} == 4 && ${BASH_VERSINFO[1]:-0} >= 4) )); then
            # since bash 4.4, @P allows variable expansion as if it were a prompt string (like PS1)
            echo -ne "\e]2;${PL_TITLEBAR@P}\a"  # set the gui window title
        else
            echo -ne "\e]2;'${PL_TITLEBAR}'\a"  # set the gui window title
        fi
    fi

    return $__return_code  # forward it to the inherited $PROMPT_COMMAND
}

# -----------------------------------------------------------------------------
# code to run after processing the inherited $PROMPT_COMMAND
function __pureline_post {
    local segment_index
    PS1=""                                  # reset the command prompt

    # load the segments
    for segment_index in "${!PL_SEGMENTS[@]}"; do
        ${PL_SEGMENTS[$segment_index]}
    done

    # final end point
    if ((${#PL_SEGMENTS[@]} > 0)); then
        PS1+="$(segment_end "$__last_color" 'Default') "
    else
        # No segments loaded, set a basic prompt
        PS1="PL | No segments Loaded: $(prompt_char)"
    fi

    # cleanup
    PS1+="${PL_COLORS[Color_Off]}"
    if [ "$PL_ERASE_TO_EOL" = true ]; then
        PS1+="\[\e[K\]"
    fi
    unset __last_color
    unset __return_code
}

# -----------------------------------------------------------------------------
# define the default color set
function set_default_colors() {
    PL_COLORS=(
        [Color_Off]='\[\e[0m\]'       # Text Reset
        # Foreground
        [Default]='\[\e[0;39m\]'      # Default
        [Black]='\[\e[0;30m\]'        # Black
        [Red]='\[\e[0;31m\]'          # Red
        [Green]='\[\e[0;32m\]'        # Green
        [Yellow]='\[\e[0;33m\]'       # Yellow
        [Blue]='\[\e[0;34m\]'         # Blue
        [Purple]='\[\e[0;35m\]'       # Purple
        # [Pink]='\[\e[1;36m\]'         # Pink
        [Cyan]='\[\e[0;36m\]'         # Cyan
        [White]='\[\e[0;37m\]'        # White
        # Background
        [On_Default]='\[\e[49m\]'     # Default
        [On_Black]='\[\e[40m\]'       # Black
        [On_Red]='\[\e[41m\]'         # Red
        [On_Green]='\[\e[42m\]'       # Green
        [On_Yellow]='\[\e[43m\]'      # Yellow
        [On_Blue]='\[\e[44m\]'        # Blue
        [On_Purple]='\[\e[45m\]'      # Purple
        [On_Cyan]='\[\e[46m\]'        # Cyan
        [On_White]='\[\e[47m\]'       # White
    )
}

# -----------------------------------------------------------------------------
# default symbols are intended for 'out-of-the-box' compatibility.
# symbols from code page 437: character set of the original IBM PC
function set_default_symbols {
    PL_SYMBOLS=(
        [hard_separator]=""
        [soft_separator]="│"

        [read_only]="Θ"
        [return_code]="x"
        [background_jobs]="↨"
        [background_jobs]="↔"
    )
}

# -----------------------------------------------------------------------------
# default set of segments
function set_default_segments {
    # PL_SEGMENTS=(
    #     'path_segment        Purple      Green'
    #     'user_segment        Black       Yellow'
    #     'read_only_segment   Red         White'
    # )
    # PL_USER_SHOW_HOST=true
    # PL_PATH_TRIM=0

    # Colors must be defined in pairs of FG & BG
    PL_COLORS[MyOrange]='\[\e[38;5;208m\]'
    PL_COLORS[On_MyOrange]='\[\e[48;5;208m\]'

    PL_COLORS[MyLime]='\[\e[38;5;119m\]'
    PL_COLORS[On_MyLime]='\[\e[48;5;119m\]'

    PL_COLORS[MyYellow]='\[\e[38;5;227m\]'
    PL_COLORS[On_MyYellow]='\[\e[48;5;227m\]'

    PL_COLORS[MyLightGrey]='\[\e[38;5;250m\]'
    PL_COLORS[On_MyLightGrey]='\[\e[48;5;250m\]'

    PL_COLORS[MyBlue]='\[\e[38;5;69m\]'
    PL_COLORS[On_MyBlue]='\[\e[48;5;69m\]'

    PL_COLORS[MyRed]='\[\e[38;5;196m\]'
    PL_COLORS[On_MyRed]='\[\e[48;5;196m\]'

    PL_COLORS[MyDarkGrey]='\[\e[38;5;240m\]'
    PL_COLORS[On_MyDarkGrey]='\[\e[48;5;240m\]'

    PL_COLORS[MyPurple]='\[\e[38;5;89m\]'
    PL_COLORS[On_MyPurple]='\[\e[48;5;89m\]'

    PL_COLORS[MyGreen]='\[\e[38;5;83m\]'
    PL_COLORS[On_MyGreen]='\[\e[48;5;83m\]'

    PL_COLORS[MyPink]='\[\e[38;5;93m\]'
    PL_COLORS[On_MyPink]='\[\e[48;5;93m\]'

    # All segments are enabled. Uncomment/comment to enable/disable a segment
    PL_SEGMENTS=(
        # segment                Background  Foreground
        # -------                ----------  ----------
        'time_segment            Black       Yellow'
        'battery_segment         MyBlue      Black'
        'ssh_segment             MyYellow    Black'
        'screen_session_segment  Black       white'
        'virtual_env_segment     MyBlue      Black'
        'conda_env_segment       MyBlue      Black'
        'aws_profile_segment     MyLime      Black'
        'kubernetes_segment      MyLime      Black'
        'os_segment              MyLime      Black'
        'path_segment            MyPurple    Yellow'
        'read_only_segment       MyRed       White'
        'background_jobs_segment MyBlue      White'
        'git_segment             MyGreen     Black'
        'return_code_segment     MyRed       White'
        'newline_segment'
        # 'duration_segment        MyDarkGrey  White'
        'user_segment            MyPink      White'
        'prompt_segment          MyDarkGrey  White'
    )

    # segment Options
    PL_PATH_TRIM=0             # 0 Full path, 1, Current, 2+ trim level
    PL_TIME_SHOW_SECONDS=true
    PL_USER_SHOW_HOST=true
    PL_USER_USE_IP=false
    PL_SSH_SHOW_HOST=true
    PL_SSH_USE_IP=true
    PL_GIT_DIRTY_FG=Black
    PL_GIT_DIRTY_BG=Green
    PL_GIT_AHEAD=true
    PL_GIT_MODIFIED=true
    PL_GIT_STAGED=true
    PL_GIT_CONFLICTS=true
    PL_GIT_UNTRACKED=true
    PL_GIT_STASH=true
    PL_PROMPT_ROOT_BG=Red
    PL_PROMPT_ROOT_FG=White

    # redefine symbols using powerline glyphs
    PL_SYMBOLS[hard_separator]=""
    PL_SYMBOLS[soft_separator]=""

    PL_SYMBOLS[git_branch]="🐈"
    PL_SYMBOLS[git_untracked]="↔"
    PL_SYMBOLS[git_stash]="§"
    PL_SYMBOLS[git_ahead]="↑"
    PL_SYMBOLS[git_behind]="↓"
    PL_SYMBOLS[git_modified]="✚ "
    PL_SYMBOLS[git_staged]="✔ "
    PL_SYMBOLS[git_conflicts]="✘ "

    PL_SYMBOLS[read_only]="👀"
    PL_SYMBOLS[return_code]="⚑"
    PL_SYMBOLS[background_jobs]="⏎"

    PL_SYMBOLS[battery_charging]="⚡"
    PL_SYMBOLS[battery_discharging]="▮"

    PL_SYMBOLS[aws_profile]='☁'
    PL_SYMBOLS[screen]='💻'
    PL_SYMBOLS[duration]='⏳'

    PL_SYMBOLS[pwd_separator]='🏝'
    PL_SYMBOLS[pwd_trimmed]='🌲'

}

# -----------------------------------------------------------------------------
# entry point to setup pureline
function main() {
    local segment_index
    local segment_function

    set_default_colors
    set_default_symbols
    set_default_segments

    # set some defaults
    PL_TITLEBAR="\u@\h: \w" # title bar setting can use PS1 style \u etc
    PL_ERASE_TO_EOL=false   # need on some terminals to prevent glitches

    # If using tmux, allow pane titles to persist
    [[ -n $TMUX ]] && unset PL_TITLEBAR

    # check if an argument has been given for a config file
    if [ -f "$1" ]; then
        # shellcheck source=/dev/null
        source "$1"
    fi

    # source external segments
    local segment_dir
    segment_dir=$(dirname "${BASH_SOURCE[0]}")'/segments'
    for segment_index in "${!PL_SEGMENTS[@]}"; do
        # check if segment function is not defined
        segment_function=${PL_SEGMENTS[$segment_index]%% *}
        if [ -z "$(type -t "$segment_function")" ]; then
            # if not defined, source external function
            # shellcheck source=/dev/null
            source "$segment_dir"'/'"$segment_function"
        fi
    done

    # dynamically set the PS1
    if [[ ! ${PROMPT_COMMAND} =~ 'pureline_ps1' ]]; then
        eval "$(echo -e "
            function pureline_ps1 {
                __pureline_pre
                $PROMPT_COMMAND
                __pureline_post
            }
        ")"
        PROMPT_COMMAND="pureline_ps1"
        # Note: defining PROMPT_COMMAND as a call to a single function simplifies a lot
        #   the integration of pureline in other prompt-modifying tools 
        #   (like the 'shell integration' feature of the integrated terminals of VSCode).
    fi
}

main "${@}"
