name: Test Nix

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Check flake metadata
        run: nix flake metadata

      - name: Build Home Manager configuration (Linux)
        run: nix build .#homeConfigurations.koji-linux.activationPackage -L --show-trace
